# 使用rasterio读取tif数据


## 1.读取单波段数据
- 准备数据路径
- 查看相关属性

### 1.1 打开tif数据

In [1]:
import rasterio

dataset = rasterio.open(r'results\output_edge_norm_sanbaoxiang.tif')
dataset

<open DatasetReader name='results\output_edge_norm_sanbaoxiang.tif' mode='r'>

- 使用`rasterio.open()`打开一个栅格文件时，返回的是一个`DataserReader`实例
- 该实例是`rasterio.io.DatasetReader`类的实例，该类有很多属性和方法，可以进一步读取栅格的数据和元信息

In [2]:
print(type(dataset))

<class 'rasterio.io.DatasetReader'>


In [ ]:
# 常用属性：波段数 int
dataset.count

1

In [ ]:
# 常用属性：行(高) 列(宽) int
dataset.height, dataset.width

(13267, 13592)

In [55]:
# 常用属性：shape tuple(int)
dataset.shape

(13267, 13592)

In [85]:
# 常用属性：无数据值
dataset.nodata 

255.0

In [ ]:
# 常用属性：范围 tuple(float)
dataset.bounds

BoundingBox(left=119.10930549419714, bottom=33.379654547232896, right=119.20716789419714, top=33.475176947232896)

In [18]:
# 继承自ruple.查看继承链
type(dataset.bounds).__mro__

(rasterio.coords.BoundingBox, tuple, object)

In [15]:
dataset.bounds[3]

33.475176947232896

In [ ]:
# 常用属性：坐标参考系 rasterio.crs.CRS
dataset.crs

CRS.from_epsg(4326)

In [21]:
type(dataset.crs).__mro__

(rasterio.crs.CRS, object)

In [ ]:
# 常用属性：transform tuple(float)
# (横向分辨率, 旋转参数，起点经度，旋转参数，-纵向分辨率，起点纬度)
# (a, b, c, d, e, f)
dataset.transform

Affine(7.199999999999764e-06, 0.0, 119.10930549419714,
       0.0, -7.200000000000009e-06, 33.475176947232896)

- 仿射变换
$$
\begin{pmatrix}
x' \\
y' \\
1
\end{pmatrix}
=
\begin{pmatrix}
a & b & c \\
d & e & f \\
0 & 0 & 1
\end{pmatrix}
\cdot
\begin{pmatrix}
x \\
y \\
1
\end{pmatrix}
$$


In [49]:
type(dataset.transform).__mro__

(affine.Affine, affine.Affine, tuple, object)

In [ ]:
# 常用属性：GDAL格式驱动 str
dataset.driver

'GTiff'

In [ ]:
# 常用属性：数据类型 tupel(str)
dataset.dtypes

('uint8',)

In [ ]:
# 常用属性：压缩 枚举类型enum.Enum(str)
dataset.compression

<Compression.lzw: 'LZW'>

In [43]:
type(dataset.compression)

<enum 'Compression'>

In [ ]:
# 常用属性：scales 和 offsets tuple(float)
# 为了存储方便，对原始物理量进行缩放和便宜，实际物理意义的值 = 原始像素值 × scale + offset
dataset.scales, dataset.offsets

((1.0,), (0.0,))

In [ ]:
# 不常用属性：
print(dataset.files)  # 文件包括附属文件 list[str]
print(dataset.block_shapes)  # 存储块的大小 list[tuple(int)]
print(dataset.name)  # 文件名带猴嘴 str
print(dataset.mode)  # 读取模式 str
print(dataset.closed)  # 开关状态 bool
print(dataset.indexes)  # 波段索引 tuple(int)

['results\\output_edge_norm_sanbaoxiang.tif', 'results\\output_edge_norm_sanbaoxiang.tif.aux.xml']
[(128, 128)]
results\output_edge_norm_sanbaoxiang.tif
r
False
(1,)


In [66]:
type(dataset.indexes)

tuple

### 1.2 读取数组

In [ ]:
dataset.read(dataset.indexes[0])  # 返回第一个波段的数组 nunpy.ndarray

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=uint8)

In [71]:
dataset.read()

array([[[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]]], dtype=uint8)

### 1.3 空间索引


In [ ]:
# 由地理位置得到像素行列  tuple(int)
dataset.index(119.15824029419714, 33.4274157472329)


(6633, 6796)

In [ ]:
# 由像素行列得到地理坐标 tuple(float)
dataset.xy(dataset.height // 2, dataset.width // 2)

(119.15824029419714, 33.4274157472329)

## 2.多波段的读取
- 主要看看read函数能直接读取吗

In [93]:
dataset = rasterio.open(r"D:\siwei_work\2025nongyezu\cropland_dl\data\js2025已修改tif\林集镇.tif")

In [ ]:
dataset.read(masked=True)  # 带掩膜的数组

masked_array(
  data=[[[--, --, --, ..., --, --, --],
         [--, --, --, ..., --, --, --],
         [--, --, --, ..., --, --, --],
         ...,
         [--, --, --, ..., --, --, --],
         [--, --, --, ..., --, --, --],
         [--, --, --, ..., --, --, --]],

        [[--, --, --, ..., --, --, --],
         [--, --, --, ..., --, --, --],
         [--, --, --, ..., --, --, --],
         ...,
         [--, --, --, ..., --, --, --],
         [--, --, --, ..., --, --, --],
         [--, --, --, ..., --, --, --]],

        [[--, --, --, ..., --, --, --],
         [--, --, --, ..., --, --, --],
         [--, --, --, ..., --, --, --],
         ...,
         [--, --, --, ..., --, --, --],
         [--, --, --, ..., --, --, --],
         [--, --, --, ..., --, --, --]]],
  mask=[[[ True,  True,  True, ...,  True,  True,  True],
         [ True,  True,  True, ...,  True,  True,  True],
         [ True,  True,  True, ...,  True,  True,  True],
         ...,
         [ True,  True,  True,

In [95]:
type(dataset.read(masked=True))

numpy.ma.core.MaskedArray

In [96]:
dataset.read()  # 不带掩膜，需要自己处理无效值

array([[[255, 255, 255, ..., 255, 255, 255],
        [255, 255, 255, ..., 255, 255, 255],
        [255, 255, 255, ..., 255, 255, 255],
        ...,
        [255, 255, 255, ..., 255, 255, 255],
        [255, 255, 255, ..., 255, 255, 255],
        [255, 255, 255, ..., 255, 255, 255]],

       [[255, 255, 255, ..., 255, 255, 255],
        [255, 255, 255, ..., 255, 255, 255],
        [255, 255, 255, ..., 255, 255, 255],
        ...,
        [255, 255, 255, ..., 255, 255, 255],
        [255, 255, 255, ..., 255, 255, 255],
        [255, 255, 255, ..., 255, 255, 255]],

       [[255, 255, 255, ..., 255, 255, 255],
        [255, 255, 255, ..., 255, 255, 255],
        [255, 255, 255, ..., 255, 255, 255],
        ...,
        [255, 255, 255, ..., 255, 255, 255],
        [255, 255, 255, ..., 255, 255, 255],
        [255, 255, 255, ..., 255, 255, 255]]], dtype=uint8)

In [97]:
dataset.read().shape  # c * h * w

(3, 9856, 14505)

In [ ]:
dataset.close()  # 关闭与文件的连接（底层的 C 库 GDAL 释放资源）

- 自动关闭
```
with rasterio.open('path') as dataset:
    data = dataset.read(1)
```
- 此时 dataset 自动关闭，不能再用 dataset.read()
